// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:shopzen_admin_dashboard/features/notification/data/model/add_notification_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddNotificationModelAdapter());
  }
}
