default_platform(:android)

platform :android do
  desc "Distribute app via Firebase App Distribution"
  lane :firebase_distribution do
    gradle(
      task: "assembleRelease",
      project_dir: "./",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: "1:131857091064:android:34bb251768b124b7bbae0d", 
      apk_path: "app/build/outputs/apk/release/app-release.apk", 
      testers: "m.alamrousi.work@gmail.com",
      release_notes: "New release via Fastlane 🚀",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"] 
    )
  end
end
